name: $(Date:yyyyMMdd)$(rev:rrr)

trigger: 
  - master

jobs:
  - job: Microsoft_Teams_Library 
    displayName: Microsoft Teams Library
    pool:
      name: Hosted Ubuntu 1604
  
    steps:
      - script: |
          yarn install
          yarn test
          yarn build
        displayName: Yarn Install, Test and Build
