variables:
  - group: InfoSec-SecurityResults

trigger:
  branches:
    include:
      - 'main'
      - 'release/*'

jobs:
  - job: Security
    displayName: 'Security Tasks'
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: tools/yaml-templates/security.yml

  - job: E2ETest2
    displayName: 'E2E Test - Default'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: tools/yaml-templates/build-app-host.yml
        parameters:
          appHostGitPath: git://$(AppHostingSdkGitPath2)@jeklouda/electronTestFailure

      - bash: 'node tools/cli/runAppsWithE2ETests.js'
        displayName: 'Run E2E integration tests'
        condition: succeeded()
        workingDirectory: '$(AppHostingSdkProjectDirectory)'

      - task: Yarn@2
        displayName: 'Run tests for electron webview'
        inputs:
          Arguments: 'run xvfb-maybe mocha'
          ProjectDirectory: '$(AppHostingSdkProjectDirectory)'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/e2e-tests-report*.xml'
          testRunTitle: 'E2E Tests - Default'
          mergeTestResults: true
        condition: succeededOrFailed()
