name: $(Date:yyyyMMdd)$(rev:rrr)

trigger: 
  - master

jobs:
  - job: Microsoft_Teams_Library 
    displayName: Microsoft Teams Library JS
    pool:
      name: Hosted VS2017
  
    steps:
      - script: |
          yarn install
          yarn test
          yarn build
        displayName: Yarn Install, Test and Build
