variables:
  - group: InfoSec-SecurityResults
  - name: products
    value: 6eff390d-80c0-4456-81b6-6abafa71e768
  - name: tags
    value: production

trigger:
  branches:
    include:
      - 'main'
      - 'release/*'

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release
    - repository: AppHostingSdk
      type: git
      name: ISS/metaos-hub-sdk
      ref: refs/heads/main
    - repository: AndroidAppHostingSdk
      type: git
      name: ISS/metaos-hub-sdk-android
    - repository: IOSAppHostingSdk
      type: git
      name: ISS/metaos-hub-sdk-ios

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    sdl:
      eslint:
        configuration: 'required'
        parser: '@typescript-eslint/parser'
        parserOptions: 'ecmaFeatures:{jsx:true}\necmaVersion:12\nsourceType:module\nproject:$(Build.SourcesDirectory)/tsconfig.common.json'
        enableExclusions: true
        exclusionPatterns": "*.d.ts\n*.spec.js\n*.spec.jsx\n*.spec.ts\n*.spec.tsx\n*.test.ts\n*.test.tsx"
        customEnvironments: true
        environmentsBrowser: true
        environmentsNode: true
        environmentsCommonJs: true
        environmentsSharedNodeBrowser: false
        environmentsEs6: false
        environmentsEs2017: false
        environmentsEs2020: true
        environmentsJest: false
      sourceRepositoriesToScan:
        include:
          - repository: AppHostingSdk
          - repository: AndroidAppHostingSdk
          - repository: IOSAppHostingSdk
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: __default
        jobs:
          - job: Security
            displayName: 'Security Tasks'
            steps:
              - template: tools/yaml-templates/security.yml@self

          - job: Build
            displayName: 'Build Test Publish'
            steps:
              - template: tools/yaml-templates/build-test-publish.yml@self

            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: 'Publish bundle analysis'
                  condition: and( in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues'), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'main'))
                  targetPath: './common/temp/bundleAnalysis'
                  artifactName: '$(bundleArtifactName)'

                - output: pipelineArtifact
                  displayName: 'Publish Test app artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\teams-test-app\$(Build.BuildId).zip'
                  artifactName: 'teams-test-app'
                  sbomBuildDropPath: '$(Build.ArtifactStagingDirectory)\teams-test-app'
                  sbomPackageName: 'teamstestappArtifact'

                - output: pipelineArtifact
                  displayName: 'Publish CDN feed to build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\CDNFeed'
                  artifactName: 'CDNFeed'

                - output: pipelineArtifact
                  displayName: 'Publish validDomains to Build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\validDomains'
                  artifactName: 'validDomains'

                - output: pipelineArtifact
                  displayName: 'Publish NPM feed to Build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\NPMFeed'
                  artifactName: 'NPMFeed'

                - output: pipelineArtifact
                  displayName: 'Publish Powershell Scripts to Build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\scripts'
                  artifactName: 'scripts'

          - job: E2ETest1
            displayName: 'E2E Test - Perf'
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: 'ubuntu-latest'
              os: linux
            steps:
              - template: tools/yaml-templates/build-app-host.yml@self
                parameters:
                  appHostGitPath: AppHostingSdk

              - task: Bash@3
                displayName: 'Run E2E Perf tests'
                condition: succeeded()
                inputs:
                  targetType: inline
                  script: 'node tools/cli/runAppsWithE2ETests.js --appUrl=https://localhost:4002 --reportFileName=e2e-tests-report-perf --envType=perf'
                  workingDirectory: '$(AppHostingSdkProjectDirectory)'

              - task: PublishTestResults@2
                inputs:
                  testResultsFormat: 'JUnit'
                  testResultsFiles: '**/e2e-tests-report*.xml'
                  testRunTitle: 'E2E Tests - Perf'
                  mergeTestResults: true
                condition: succeededOrFailed()

          - job: E2ETest2
            displayName: 'E2E Test - Default'
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: 'ubuntu-2004'
              os: linux
            steps:
              - template: tools/yaml-templates/build-app-host.yml@self
                parameters:
                  appHostGitPath: AppHostingSdk

              - bash: 'node tools/cli/runAppsWithE2ETests.js --useDataFromLocal=true'
                displayName: 'Run E2E integration tests'
                condition: succeeded()
                workingDirectory: '$(AppHostingSdkProjectDirectory)'

              - task: CMDLine@2
                displayName: 'Run tests for electron webview'
                inputs:
                  script: |
                    pnpm exec xvfb-maybe playwright test
                  workingDirectory: '$(AppHostingSdkProjectDirectory)'

              - task: PublishTestResults@2
                inputs:
                  testResultsFormat: 'JUnit'
                  testResultsFiles: '**/e2e-tests-report*.xml'
                  testRunTitle: 'E2E Tests - Default'
                  mergeTestResults: true
                condition: succeededOrFailed()

          - job: E2ETest3
            displayName: 'E2E Test - Local Tag'
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: 'ubuntu-latest'
              os: linux
            steps:
              - template: tools/yaml-templates/build-app-host.yml@self
                parameters:
                  appHostGitPath: AppHostingSdk

              - task: CmdLine@2
                displayName: 'Build Test App Local'
                inputs:
                  script: |
                    pnpm build-test-app-local
                  workingDirectory: '$(ClientSdkProjectDirectory)'

              - bash: 'node tools/cli/runAppsWithE2ETests.js --useDataFromLocal=true --reportFileName=e2e-tests-report-local-script-tag --envType=localScriptTag'
                displayName: 'Run E2E integration tests with local script tag'
                condition: succeeded()
                workingDirectory: '$(AppHostingSdkProjectDirectory)'

              - task: PublishTestResults@2
                inputs:
                  testResultsFormat: 'JUnit'
                  testResultsFiles: '**/e2e-tests-report*.xml'
                  testRunTitle: 'E2E Tests - Local Tag'
                  mergeTestResults: true
                condition: succeededOrFailed()

          - job: E2ETestCDN
            displayName: 'E2E Test - CDN (only runs on release builds)'
            # This test only runs after deployment from a release branch and the new CDN version has been deployed
            # This check will run on the PR to merge the release branch back into main
            condition: and(
              eq(variables['Build.Reason'], 'PullRequest'),
              startsWith(variables['System.PullRequest.SourceBranch'], 'release/'),
              eq(variables['System.PullRequest.TargetBranch'], 'main')
              )
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: 'ubuntu-latest'
              os: linux
            steps:
              - template: tools/yaml-templates/build-app-host.yml@self
                parameters:
                  appHostGitPath: AppHostingSdk

              - task: CmdLine@2
                displayName: 'Build Test App CDN'
                inputs:
                  script: |
                    pnpm build-test-app-CDN
                  workingDirectory: '$(ClientSdkProjectDirectory)'

              - bash: 'node tools/cli/runAppsWithE2ETests.js --useDataFromLocal=true --reportFileName=e2e-tests-report-cdn-script-tag --envType=cdnScriptTag'
                displayName: 'Run E2E integration tests with local script tag on latest cdn bundles'
                condition: succeeded()
                workingDirectory: '$(AppHostingSdkProjectDirectory)'
                enabled: true

              - task: PublishTestResults@2
                inputs:
                  testResultsFormat: 'JUnit'
                  testResultsFiles: '**/e2e-tests-report*.xml'
                  testRunTitle: 'E2E Tests - CDN'
                  mergeTestResults: true
                condition: succeededOrFailed()

          - job: E2ETestAndroid
            displayName: 'E2E Test - Android'
            pool:
              name: Azure Pipelines
              image: internal-macos12
              os: macOS
            steps:
              - template: tools/yaml-templates/android-test.yml@self
                parameters:
                  androidAppHostingSdkGitPath: AndroidAppHostingSdk

          - job: E2ETestIOS
            displayName: 'E2E Test - IOS'
            pool:
              name: Azure Pipelines
              image: internal-macos12
              os: macOS
            steps:
              - template: tools/yaml-templates/ios-test.yml@self
                parameters:
                  iOSAppHostingSdkGitPath: IOSAppHostingSdk

          - job: E2ETestIOS-backcompat
            displayName: 'E2E Test - IOS - backcompat'
            pool:
              name: Azure Pipelines
              image: internal-macos12
              os: macOS
            steps:
              - checkout: self
              - checkout: IOSAppHostingSdk

              - task: Bash@3
                displayName: 'Install XCTestHtmlReport for publishing result'
                inputs:
                  targetType: inline
                  script: |
                    brew install xctesthtmlreport
                  workingDirectory: '$(System.DefaultWorkingDirectory)'

              - task: NodeTool@0
                inputs:
                  versionSpec: '18.x'
                displayName: 'Install Node.js'

              - task: Cache@2
                inputs:
                  key: 'pnpm | "$(Agent.OS)" | $(ClientSdkProjectDirectory)/pnpm-lock.yaml'
                  path: $(Pipeline.Workspace)/.pnpm-store
                displayName: Cache pnpm

              - task: CmdLine@2
                displayName: 'Setup pnpm'
                inputs:
                  script: |
                    corepack enable
                    corepack prepare pnpm@7.30.1 --activate
                    pnpm config set store-dir $(Pipeline.Workspace)/.pnpm-store

              - task: CmdLine@2
                displayName: 'Install client sdk dependencies'
                inputs:
                  script: |
                    pnpm install
                  workingDirectory: '$(ClientSdkProjectDirectory)'

              - task: CmdLine@2
                displayName: 'Build client sdk'
                inputs:
                  script: |
                    pnpm build-force-blazor
                  workingDirectory: '$(ClientSdkProjectDirectory)'

              - task: Bash@3
                displayName: 'Run sample test app in background'
                inputs:
                  targetType: inline
                  script: 'nohup pnpm start-test-app &'
                  workingDirectory: '$(ClientSdkProjectDirectory)'

              - task: Bash@3
                displayName: 'Disable Slow Animation'
                inputs:
                  targetType: inline
                  script: cd ~/Library/Preferences defaults write com.apple.iphonesimulator SlowMotionAnimation -bool NO
                  workingDirectory: '$(System.DefaultWorkingDirectory)'

              - task: CmdLine@2
                displayName: 'Build iOS UI/E2E Tests'
                inputs:
                  script: |
                    cd backcompattool
                    ls
                  workingDirectory: '$(Agent.BuildDirectory)/iOSHost'

              - task: Bash@3
                displayName: 'iOS UI/E2E Tests'
                inputs:
                  targetType: inline
                  script: "/usr/bin/xcodebuild -configuration Release -workspace /Users/runner/work/1/iOSHost/$(IOSSdkWorkspace).xcworkspace -scheme $(IOSSdkScheme) -sdk iphonesimulator -parallel-testing-enabled YES -parallel-testing-worker-count 2 -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' -screenshot-enabled=\"YES\" -quiet -resultBundlePath TestResults test 2>/dev/null\nif [[ $? == 0 ]]; then echo \"E2E Test passes successfully\"; exit 0; else echo \"E2E Test failed\"; exit 1; fi;"
                  workingDirectory: '$(Agent.BuildDirectory)/iOSHost'

              - task: Bash@3
                displayName: 'Generate E2E test report'
                condition: succeededOrFailed()
                inputs:
                  targetType: inline
                  script: |
                    xchtmlreport -r TestResults -j; if [[ $? == 0 ]]; then echo "Test report has been generated successfully."; exit 0; else echo "Test report generating process failed for some reasons."; exit 1; fi;
                  workingDirectory: '$(Agent.BuildDirectory)/iOSHost'

              - task: PublishTestResults@2
                displayName: 'Publish Test Results'
                inputs:
                  testResultsFiles: '**/*.junit'
                  failTaskOnFailedTests: false
                  testRunTitle: 'E2E Tests - iOS'
                  searchFolder: '$(Agent.BuildDirectory)/iOSHost'
                  mergeTestResults: true
                condition: always()
