# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# The Task 'PublishBuildArtifacts@1' have been converted to an output named 'Publish bundle analysis' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' have been converted to an output named 'Publish Test app artifacts' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' have been converted to an output named 'Publish CDN feed to build Artifacts' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' have been converted to an output named 'Publish NPM feed to Build Artifacts' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' have been converted to an output named 'Publish Powershell Scripts to Build Artifacts' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' have been converted to an output named 'Publish SBOM to Build Artifacts' in the templateContext section.
variables:
  - group: InfoSec-SecurityResults
  - name: products
    value: 6eff390d-80c0-4456-81b6-6abafa71e768
  - name: tags
    value: production
trigger:
  branches:
    include:
      - 'main'
      - 'release/*'
resources:
  repositories:
    - repository: CustomPipelineTemplates
      type: git
      name: OE/OfficePipelineTemplates
      ref: refs/heads/main
extends:
  template: v1/Office.Official.PipelineTemplate.yml@CustomPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      # sourceRepositoriesToScan:
      # include:
      # - repository: git://$(AppHostingSdkGitPath)@$(AppHostingSdkGitRef)
      # - repository: git://$(AndroidAppHostingSdkGitPath)
      # - repository: git://$(IOSAppHostingSdkGitPath)
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: __default
        jobs:
          - job: Security
            displayName: 'Security Tasks'
            steps:
              - task: ESLint@1
                displayName: 'Run ESLint'
                inputs:
                  Configuration: 'required'
                  TargetType: 'eslint'
                  TargetsESLint: '$(Build.SourcesDirectory)/**/*.{js,jsx,ts,tsx}'
                  Parser: '@typescript-eslint/parser'
                  ParserOptions: |
                    sourceType:module
                    ecmaVersion:2018
                  ErrorLevel: 'warn'
                  ExitOnFatalError: true
              - task: CredScan@3
                displayName: 'Run Credential Scanner'
                condition: succeededOrFailed()
                inputs:
                  debugMode: false
                  suppressionsFile: '.sdl\CredScanSuppressions.json'
              - task: PublishSecurityAnalysisLogs@3
                inputs:
                  ArtifactName: 'CodeAnalysisLogs'
                  ArtifactType: 'M365'
                  AllTools: true
                  ToolLogsNotFoundAction: 'Standard'
                condition: succeededOrFailed()
                displayName: 'Publish Guardian Artifacts 2'
              - task: AssetRetention@3
                inputs:
                  ArrowServiceConnection: '$(ArrowConnection)'
                  AssetGroupName: '$(System.TeamProject)_$(Build.DefinitionName)'
                  AssetNumber: '$(Build.BuildId)'
                  IsShipped: false
                  DropsToRetain: 'CodeAnalysisLogs'
                condition: and( or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')), ne(variables['Build.Reason'], 'PullRequest') )
                displayName: 'Artifact Retention(Arrow)'
              - task: PostAnalysis@2
                condition: succeededOrFailed()
                displayName: 'Guardian Break'
                inputs:
                  GdnBreakPolicyMinSev: Warning
                  GdnBreakAllTools: true
                  GdnBreakGdnToolCredScan: true
                  GdnBreakGdnToolCredScanSeverity: Warning
                  GdnBreakGdnToolESLint: true
                  GdnBreakGdnToolESLintSeverity: Warning
                  GdnBreakPolicy: M365
              - task: ComponentGovernanceComponentDetection@0
                condition: eq(variables['Build.Reason'], 'PullRequest')
                inputs:
                  scanType: 'LogOnly'
                  verbosity: 'Verbose'
                  alertWarningLevel: 'High'
                  failOnAlert: true
                displayName: 'Component Governance (Pull Request)'
              - task: ComponentGovernanceComponentDetection@0
                condition: and( or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')), ne(variables['Build.Reason'], 'PullRequest'))
                displayName: 'Component Governance (main, release)'
